#define SCRIPTPATH LAxemann\RR_mapStuff\addons\RR_mapStuff_main
#define PREFIX RR_mapStuff
#define DECLAREFNC(FNCNAME,PREFIX,SCRIPTPATH) PREFIX##_fnc_##FNCNAME = compile preprocessFileLineNumbers 'SCRIPTPATH##\fncs\##FNCNAME##.sqf' ;


#include "functions.inc"


/*
    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!
	!! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!
*/

